FROM node:18-alpine3.16
WORKDIR /app
COPY ["package.json", "yarn.lock", "./"]
COPY .env .env
RUN  yarn install --registry http://registry.npmmirror.com  --force
COPY . .
EXPOSE 12833
CMD ["yarn", "run", "start"]
